<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace>andecr</RootNamespace>
    <AssemblyName>andecr</AssemblyName>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.4" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.17"
                      Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="ReactiveUI.Avalonia" Version="12.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\DeckSelectionView.axaml.cs">
      <DependentUpon>DeckSelectionView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\EnglishDeckView.axaml.cs">
      <DependentUpon>EnglishDeckView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\EstonianDeckView.axaml.cs">
      <DependentUpon>EstonianDeckView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <!-- Все файлы в Assets/ автоматически -->
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
</Project>
